name: 🚀 Deploy website on push

on: 
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: ✨ Build Storybook  
      run: |
        npm i
        npm run build-storybook
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER_NAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: storybook-static/
        server-dir: public_html/storybook/
